-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "scoreTeamA" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scoreTeamB" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_winnerId_fkey" FOREIGN KEY ("winnerId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;
